baseURL = "https://invmv.github.io/Notion-Hugo-theme-diary/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-hant"
theme = "diary"

title = "A Hugo Site"
copyright = "This is a customized copyright."

# RobotsTXT
enableRobotsTXT = true

#  开启中文、日文、韩文字符识别，默认为 false
hasCJKLanguage = true
# summary 
summaryLength = 100 

# [markup]
#   [markup.highlight]
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ""
#     lineNoStart = 1
#     lineNos = false
#     lineNumbersInTable = true
#     noClasses = true
#     style = "perldoc"
#     tabWidth = 4

# [services]
#   [services.disqus]
#     shortname = 'your-disqus-shortname'
#   [services.googleAnalytics]
#     ID = 'G-MEASUREMENT_ID'

[params]
favicon = "favicon.ico"
# images = ['site-feature-image.jpg']
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'
subtitle = "Themed by Diary."

enableGitalk = false
enableGiscus = false

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true

# Cloudflare Web Analytics
# cloudflareToken = "your cloudflare web analytics token"

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
# clarity = "abcdefghzd"

# Google Search Box
# googleSearchCode = "Your Search Code"

# [params.gitalk]
#   owner = "user"
#   repo = "repo name"
#   client_id = "your client id"
#   client_secret = "your client secret"


# [params.utterances]
# repo="your repo"
# term="[ENTER TERM HERE]"
# label="your label"
# theme="github-light"

# Please visit https://giscus.app/ to generate settings.
# [params.giscus]
#     data_repo="username/repo"
#     data_repo_id="**************************"    
#     data_category="General"
#     data_category_id="*********************"
#     data_mapping="pathname"
#     data_strict="0"
#     data_reactions_enabled="1"
#     data_emit_metadata="0"
#     data_input_position="bottom"
#     data_theme="preferred_color_scheme"
#     data_lang="en"
#     crossorigin="anonymous"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4

[outputs]
home = ["HTML", "RSS", "JSON"]

[permalinks]
  [permalinks.page]
    posts = '/:title/'
    page = '/:title/'